### ISSUE TITLE
a couple of features I would like.

### ISSUE THREAD

**Issue by BubbaSWalter** [t2t2/obs-tablet-remote#13] opened 2017-10-16 06:43 UTC
I would like to have to option to show chat and stream window.  Kind of like how the Original OBS remote has it.

**Comment by t2t2** [comment] 2017-10-16 08:18
Duplicate of #9 (which becomes just providing generic iframe embed, maybe some UI to autogenerate URLs for common services embed & chat)

**Closed** 2017-10-16 08:18 UTC
