### ISSUE TITLE
[Feature Request] Keyboard shortcuts?

### ISSUE THREAD

**Issue by ITCMD** [t2t2/obs-tablet-remote#59] opened 2020-01-27 16:12 UTC
I'm not sure if this would be easy to impliment, but configurable keyboard shortcuts to swap scenes would be extremely helpful if it could be added in. Great program though!

**Comment by t2t2** [comment] 2020-02-01 23:48
Duplicate of #8

**Closed** 2020-02-01 23:49 UTC
Labels: duplicate
